{
    'name': 'Account Generic Customisation',
    'version': '18.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Add reference date and remarks fields to account payments',
    'description': """""",
    "website": "https://code-ox.com/",
    "author": "Code-Ox Technologies",
    "license": "AGPL-3",
    'depends': ['account', 'om_account_accountant'],
    'data': [
        'security/ir.model.access.csv',
        'views/account_payment_views.xml',
        'views/account_account.xml',
        'views/account_move.xml',
        'views/chart_of_accounts.xml',
        'views/account_asset.xml',
        'views/account_sub_group.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}