# -*- coding: utf-8 -*-

from . import sms_gateway
from . import subscription_plan
from . import subscription_package
from . import subscription_products
from . import subscription_order
from . import subscription_close
from . import subscription_renew
from . import plan_choice
from . import customer_referrals
from . import customer_device_token
from . import account_move
from . import account_payment_register
from . import customer_goals
from . import res_partner
from . import sale_order
from . import plan_category
from . import subscription_plan_choice
from . import product_brand
from . import product_template
from . import recurrence_period
from . import meal_ingredient_category
from . import weekly_meal
from . import meals_category
from . import meals_count
from . import meals_tag
from . import tag_information
from . import customer_street
from . import customer_district
from . import customer_shift
from . import customer_zone
from . import res_company
from . import res_config_settings
from . import ir_attachment
from . import customer_meal_calendar
from . import recipe
from . import kitchen_type
from . import subscription_extension_reason
from . import coupons
from . import driver_notification
from . import driver
from . import product_category,day_shift
from . import hr_employee
from . import dietitian_appointment_history
from . import customer_health_history
from . import customer_notification
from . import customer_notification_schedule
from . import special_offer
from . import universal_pause_days
from . import plan_default_meals
from . import customer_account_deletion
from . import diet_eshop_sale
from . import referral_config
from . import birthday_calender
from . import res_country_state
from . import customer_goals
from . import res_company
from . import terms_and_condtions
from . import ramdan_process_log
